### ISSUE TITLE
Best way to make fishpal() function adaptive, but with core color defaults?

### ISSUE THREAD

**Issue by Myfanwy** [fishsciences/fishpals#1]
Ideally, I'd like there to be 5-10 "core" colors from each fish species to which the `fish_pal()` function defaults.  If more colors are necessary, `colorRampPalette()` should start with those core colors and generate more hues from there.  How to do this?

The`fish_pal()` function is basically exactly the same as @karthik 's `wesanderson::wes_palette()` function right now.  I know viridis works off of a sort of dataframe of 1024 RGB values, but I like @karthik 's concise use of the `colorRamPalette()` function. I think to avoid hitting palette color limits, though, I'd have to generate each fish palette to have at least 255 colors, yes?

**Comment by hrbrmstr** [comment]
For discrete, we shld (IMO) have a def upper limit.

We can be more flexible with the continuous one and lemme see what I can do vis-a-vis taking your fish samples and extracting more base color data from the fish themselves and then sorting the colors and have that available for a more "completely fishy" ramp.

**Comment by Myfanwy** [comment]
I cut the color palettes down to the core colors for each of the three fish pals there right now.  Next task is to generate 255 colors from each core color, and build in defaults to the `fishpal()` function so that it uses the core colors first, then fills in from the rest.

**Comment by Myfanwy** [comment]
So ^ turned out to be kinda hard and maybe not necessary... have left it as is for now, where "continuous" is the default scale type - you do have to specify an `n` for color values, but I think the adaptability that `viridis` has for this type of palette-building is probably beyond the scope of this package at the moment - I have no idea how to make the function auto-detect how many variables the user is interested in mapping to the color/fill aesthetics.
